// <auto-generated />
using System;
using LtcCognitive.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace LtcCognitive.Api.Data.Migrations
{
    [DbContext(typeof(LtcDbContext))]
    [Migration("20260721094111_InitialNineTableSchema")]
    partial class InitialNineTableSchema
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("LtcCognitive.Api.Domain.AssessmentSession", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("session_id");

                    b.Property<string>("CompletionStatus")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("completion_status");

                    b.Property<DateTimeOffset>("EndedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("ended_at_utc");

                    b.Property<string>("ExitReason")
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("exit_reason");

                    b.Property<Guid>("GameId")
                        .HasColumnType("uuid")
                        .HasColumnName("game_id");

                    b.Property<long>("PlayerId")
                        .HasColumnType("bigint")
                        .HasColumnName("player_id");

                    b.Property<DateTimeOffset>("ReceivedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("received_at_utc");

                    b.Property<string>("SchemaVersion")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("schema_version");

                    b.Property<DateTimeOffset>("StartedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("started_at_utc");

                    b.Property<string>("TaskVersion")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("task_version");

                    b.HasKey("Id")
                        .HasName("pk_assessment_session");

                    b.HasIndex("GameId");

                    b.HasIndex("PlayerId", "StartedAtUtc")
                        .HasDatabaseName("ix_assessment_player_started");

                    b.ToTable("assessment_session", "cognitive", t =>
                        {
                            t.HasCheckConstraint("ck_assessment_time", "ended_at_utc >= started_at_utc");
                        });
                });

            modelBuilder.Entity("LtcCognitive.Api.Domain.CognitiveDomain", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("domain_id");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("domain_code");

                    b.Property<string>("Description")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("description");

                    b.Property<string>("NameZhTw")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("name_zh_tw");

                    b.HasKey("Id")
                        .HasName("pk_cognitive_domain");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("uq_cognitive_domain_code");

                    b.ToTable("cognitive_domain", "cognitive");

                    b.HasData(
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000001"),
                            Code = "attention_inhibition",
                            NameZhTw = "注意力與抑制控制"
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000002"),
                            Code = "processing_speed",
                            NameZhTw = "處理速度與視覺搜尋"
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000003"),
                            Code = "executive_reasoning",
                            NameZhTw = "執行功能與數字推理"
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000004"),
                            Code = "visual_working_memory",
                            NameZhTw = "視覺工作記憶"
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000005"),
                            Code = "visuospatial_planning",
                            NameZhTw = "視空間規劃與問題解決"
                        });
                });

            modelBuilder.Entity("LtcCognitive.Api.Domain.CoinTransaction", b =>
                {
                    b.Property<long>("TransactionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("transaction_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<long>("TransactionId"));

                    b.Property<int>("Amount")
                        .HasColumnType("integer")
                        .HasColumnName("amount");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<long>("PlayerId")
                        .HasColumnType("bigint")
                        .HasColumnName("player_id");

                    b.Property<string>("ReferenceKey")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("reference_key");

                    b.Property<string>("TransactionType")
                        .IsRequired()
                        .HasMaxLength(24)
                        .HasColumnType("character varying(24)")
                        .HasColumnName("transaction_type");

                    b.HasKey("TransactionId")
                        .HasName("pk_coin_transaction");

                    b.HasIndex("PlayerId", "TransactionType", "ReferenceKey")
                        .IsUnique()
                        .HasDatabaseName("uq_coin_source");

                    b.ToTable("coin_transaction", "ltc", t =>
                        {
                            t.HasCheckConstraint("ck_coin_amount_nonzero", "amount <> 0");
                        });
                });

            modelBuilder.Entity("LtcCognitive.Api.Domain.DerivedMetric", b =>
                {
                    b.Property<long>("MetricId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("metric_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<long>("MetricId"));

                    b.Property<string>("CalculationVersion")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("calculation_version");

                    b.Property<Guid>("DomainId")
                        .HasColumnType("uuid")
                        .HasColumnName("domain_id");

                    b.Property<string>("MetricCode")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("metric_code");

                    b.Property<string>("QualityFlag")
                        .IsRequired()
                        .HasMaxLength(24)
                        .HasColumnType("character varying(24)")
                        .HasColumnName("quality_flag");

                    b.Property<Guid>("SessionId")
                        .HasColumnType("uuid")
                        .HasColumnName("session_id");

                    b.Property<string>("Unit")
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("unit");

                    b.Property<double>("Value")
                        .HasColumnType("double precision")
                        .HasColumnName("value");

                    b.HasKey("MetricId")
                        .HasName("pk_derived_metric");

                    b.HasIndex("DomainId");

                    b.HasIndex("SessionId", "DomainId", "MetricCode")
                        .IsUnique()
                        .HasDatabaseName("uq_metric_session_domain_code");

                    b.ToTable("derived_metric", "cognitive");
                });

            modelBuilder.Entity("LtcCognitive.Api.Domain.GameDefinition", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("game_id");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("game_code");

                    b.Property<Guid>("DomainId")
                        .HasColumnType("uuid")
                        .HasColumnName("domain_id");

                    b.Property<string>("EvidenceNote")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("evidence_note");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("MappingVersion")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("mapping_version");

                    b.Property<string>("NameZhTw")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("name_zh_tw");

                    b.HasKey("Id")
                        .HasName("pk_game");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("uq_game_code");

                    b.HasIndex("DomainId");

                    b.ToTable("game", "cognitive");

                    b.HasData(
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0000-000000000001"),
                            Code = "stroop_color_match",
                            DomainId = new Guid("10000000-0000-0000-0000-000000000001"),
                            EvidenceNote = "Stroop 作業：選擇性注意與反應抑制。",
                            IsActive = true,
                            MappingVersion = "1.0",
                            NameZhTw = "顏色文字判斷"
                        },
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0000-000000000002"),
                            Code = "number_order",
                            DomainId = new Guid("10000000-0000-0000-0000-000000000002"),
                            EvidenceNote = "視覺搜尋、排序與處理速度。",
                            IsActive = true,
                            MappingVersion = "1.0",
                            NameZhTw = "數字由小到大"
                        },
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0000-000000000003"),
                            Code = "number_sum",
                            DomainId = new Guid("10000000-0000-0000-0000-000000000003"),
                            EvidenceNote = "工作記憶、策略選擇與數字推理。",
                            IsActive = true,
                            MappingVersion = "1.0",
                            NameZhTw = "數字組合加總"
                        },
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0000-000000000004"),
                            Code = "card_memory",
                            DomainId = new Guid("10000000-0000-0000-0000-000000000004"),
                            EvidenceNote = "視覺位置的編碼、保持與提取。",
                            IsActive = true,
                            MappingVersion = "1.0",
                            NameZhTw = "翻卡牌"
                        },
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0000-000000000005"),
                            Code = "pipe_rotation",
                            DomainId = new Guid("10000000-0000-0000-0000-000000000005"),
                            EvidenceNote = "心像旋轉、空間規劃與問題解決。",
                            IsActive = true,
                            MappingVersion = "1.0",
                            NameZhTw = "旋轉接水管"
                        });
                });

            modelBuilder.Entity("LtcCognitive.Api.Domain.Item", b =>
                {
                    b.Property<int>("ItemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("item_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<int>("ItemId"));

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("ItemCode")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("item_code");

                    b.Property<string>("ItemType")
                        .IsRequired()
                        .HasMaxLength(24)
                        .HasColumnType("character varying(24)")
                        .HasColumnName("item_type");

                    b.Property<string>("NameZhTw")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("name_zh_tw");

                    b.Property<int>("Price")
                        .HasColumnType("integer")
                        .HasColumnName("price");

                    b.HasKey("ItemId")
                        .HasName("pk_item");

                    b.HasIndex("ItemCode")
                        .IsUnique()
                        .HasDatabaseName("uq_item_code");

                    b.ToTable("item", "ltc", t =>
                        {
                            t.HasCheckConstraint("ck_item_price", "price >= 0");
                        });
                });

            modelBuilder.Entity("LtcCognitive.Api.Domain.Player", b =>
                {
                    b.Property<long>("PlayerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("player_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<long>("PlayerId"));

                    b.Property<string>("AuthProvider")
                        .IsRequired()
                        .HasMaxLength(24)
                        .HasColumnType("character varying(24)")
                        .HasColumnName("auth_provider");

                    b.Property<string>("AuthSubjectHash")
                        .IsRequired()
                        .HasColumnType("character(64)")
                        .HasColumnName("auth_subject_hash");

                    b.Property<short?>("BirthYear")
                        .HasColumnType("smallint")
                        .HasColumnName("birth_year");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("display_name");

                    b.Property<string>("EducationLevelCode")
                        .HasMaxLength(24)
                        .HasColumnType("character varying(24)")
                        .HasColumnName("education_level_code");

                    b.Property<DateTimeOffset>("LastLoginAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_login_at_utc");

                    b.Property<string>("PlayerCode")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("player_code");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("status");

                    b.HasKey("PlayerId")
                        .HasName("pk_player");

                    b.HasIndex("PlayerCode")
                        .IsUnique()
                        .HasDatabaseName("uq_player_code");

                    b.HasIndex("AuthProvider", "AuthSubjectHash")
                        .IsUnique()
                        .HasDatabaseName("uq_player_auth_subject");

                    b.ToTable("player", "ltc", t =>
                        {
                            t.HasCheckConstraint("ck_player_birth_year", "birth_year IS NULL OR birth_year BETWEEN 1900 AND 2100");

                            t.HasCheckConstraint("ck_player_status", "status IN ('active', 'suspended', 'deleted')");
                        });
                });

            modelBuilder.Entity("LtcCognitive.Api.Domain.PlayerInventory", b =>
                {
                    b.Property<long>("PlayerId")
                        .HasColumnType("bigint")
                        .HasColumnName("player_id");

                    b.Property<int>("ItemId")
                        .HasColumnType("integer")
                        .HasColumnName("item_id");

                    b.Property<DateTimeOffset>("AcquiredAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("acquired_at_utc");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer")
                        .HasColumnName("quantity");

                    b.HasKey("PlayerId", "ItemId")
                        .HasName("pk_player_inventory");

                    b.HasIndex("ItemId");

                    b.ToTable("player_inventory", "ltc", t =>
                        {
                            t.HasCheckConstraint("ck_inventory_quantity", "quantity >= 0");
                        });
                });

            modelBuilder.Entity("LtcCognitive.Api.Domain.TrialEvent", b =>
                {
                    b.Property<Guid>("SessionId")
                        .HasColumnType("uuid")
                        .HasColumnName("session_id");

                    b.Property<short>("TrialIndex")
                        .HasColumnType("smallint")
                        .HasColumnName("trial_index");

                    b.Property<string>("ActualResponse")
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("actual_response");

                    b.Property<string>("ExpectedResponse")
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("expected_response");

                    b.Property<bool?>("IsCorrect")
                        .HasColumnType("boolean")
                        .HasColumnName("is_correct");

                    b.Property<int?>("PresentationDurationMs")
                        .HasColumnType("integer")
                        .HasColumnName("presentation_duration_ms");

                    b.Property<int?>("ReactionTimeMs")
                        .HasColumnType("integer")
                        .HasColumnName("reaction_time_ms");

                    b.Property<string>("StimulusJson")
                        .HasColumnType("jsonb")
                        .HasColumnName("stimulus_json");

                    b.Property<string>("TrialType")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("trial_type");

                    b.HasKey("SessionId", "TrialIndex")
                        .HasName("pk_trial_event");

                    b.ToTable("trial_event", "cognitive");
                });

            modelBuilder.Entity("LtcCognitive.Api.Domain.AssessmentSession", b =>
                {
                    b.HasOne("LtcCognitive.Api.Domain.GameDefinition", "Game")
                        .WithMany("Sessions")
                        .HasForeignKey("GameId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("LtcCognitive.Api.Domain.Player", "Player")
                        .WithMany("Assessments")
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Game");

                    b.Navigation("Player");
                });

            modelBuilder.Entity("LtcCognitive.Api.Domain.CoinTransaction", b =>
                {
                    b.HasOne("LtcCognitive.Api.Domain.Player", "Player")
                        .WithMany("CoinTransactions")
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Player");
                });

            modelBuilder.Entity("LtcCognitive.Api.Domain.DerivedMetric", b =>
                {
                    b.HasOne("LtcCognitive.Api.Domain.CognitiveDomain", "Domain")
                        .WithMany()
                        .HasForeignKey("DomainId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("LtcCognitive.Api.Domain.AssessmentSession", "Session")
                        .WithMany("Metrics")
                        .HasForeignKey("SessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Domain");

                    b.Navigation("Session");
                });

            modelBuilder.Entity("LtcCognitive.Api.Domain.GameDefinition", b =>
                {
                    b.HasOne("LtcCognitive.Api.Domain.CognitiveDomain", "Domain")
                        .WithMany("Games")
                        .HasForeignKey("DomainId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Domain");
                });

            modelBuilder.Entity("LtcCognitive.Api.Domain.PlayerInventory", b =>
                {
                    b.HasOne("LtcCognitive.Api.Domain.Item", "Item")
                        .WithMany("Owners")
                        .HasForeignKey("ItemId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("LtcCognitive.Api.Domain.Player", "Player")
                        .WithMany("Inventory")
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Item");

                    b.Navigation("Player");
                });

            modelBuilder.Entity("LtcCognitive.Api.Domain.TrialEvent", b =>
                {
                    b.HasOne("LtcCognitive.Api.Domain.AssessmentSession", "Session")
                        .WithMany("Trials")
                        .HasForeignKey("SessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Session");
                });

            modelBuilder.Entity("LtcCognitive.Api.Domain.AssessmentSession", b =>
                {
                    b.Navigation("Metrics");

                    b.Navigation("Trials");
                });

            modelBuilder.Entity("LtcCognitive.Api.Domain.CognitiveDomain", b =>
                {
                    b.Navigation("Games");
                });

            modelBuilder.Entity("LtcCognitive.Api.Domain.GameDefinition", b =>
                {
                    b.Navigation("Sessions");
                });

            modelBuilder.Entity("LtcCognitive.Api.Domain.Item", b =>
                {
                    b.Navigation("Owners");
                });

            modelBuilder.Entity("LtcCognitive.Api.Domain.Player", b =>
                {
                    b.Navigation("Assessments");

                    b.Navigation("CoinTransactions");

                    b.Navigation("Inventory");
                });
#pragma warning restore 612, 618
        }
    }
}
