// <auto-generated />
using System;
using LtcCognitive.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace LtcCognitive.Api.Data.Migrations
{
    [DbContext(typeof(LtcDbContext))]
    [Migration("20260720060028_InitialCognitiveSchema")]
    partial class InitialCognitiveSchema
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("cognitive")
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("LtcCognitive.Api.Domain.AssessmentSession", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int?>("ClientTimezoneOffsetMinutes")
                        .HasColumnType("integer");

                    b.Property<string>("CompletionStatus")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("DeviceId")
                        .HasColumnType("uuid");

                    b.Property<int>("DurationMs")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("EndedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ExitReason")
                        .HasColumnType("text");

                    b.Property<Guid>("GameId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ParticipantId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("ReceivedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("SchemaVersion")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("StartedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("TaskVersion")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("DeviceId");

                    b.HasIndex("GameId");

                    b.HasIndex("ParticipantId", "StartedAtUtc");

                    b.ToTable("AssessmentSessions", "cognitive", t =>
                        {
                            t.HasCheckConstraint("ck_session_duration", "\"DurationMs\" >= 0");
                        });
                });

            modelBuilder.Entity("LtcCognitive.Api.Domain.CognitiveDomain", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("NameZhTw")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("CognitiveDomains", "cognitive");

                    b.HasData(
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000001"),
                            Code = "attention_inhibition",
                            NameZhTw = "注意力與抑制控制"
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000002"),
                            Code = "processing_speed",
                            NameZhTw = "處理速度與視覺搜尋"
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000003"),
                            Code = "executive_reasoning",
                            NameZhTw = "執行功能與數字推理"
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000004"),
                            Code = "visual_working_memory",
                            NameZhTw = "視覺空間工作記憶"
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000005"),
                            Code = "visuospatial_planning",
                            NameZhTw = "視空間規劃與問題解決"
                        });
                });

            modelBuilder.Entity("LtcCognitive.Api.Domain.DerivedMetric", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("CalculationVersion")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("DomainId")
                        .HasColumnType("uuid");

                    b.Property<string>("MetricCode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("QualityFlag")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("SessionId")
                        .HasColumnType("uuid");

                    b.Property<string>("Unit")
                        .HasColumnType("text");

                    b.Property<double>("Value")
                        .HasColumnType("double precision");

                    b.HasKey("Id");

                    b.HasIndex("DomainId");

                    b.HasIndex("SessionId", "MetricCode", "DomainId")
                        .IsUnique();

                    b.ToTable("DerivedMetrics", "cognitive");
                });

            modelBuilder.Entity("LtcCognitive.Api.Domain.Device", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<float?>("Dpi")
                        .HasColumnType("real");

                    b.Property<DateTimeOffset>("FirstSeenAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("InstallationId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("LastSeenAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Model")
                        .HasColumnType("text");

                    b.Property<string>("Platform")
                        .HasColumnType("text");

                    b.Property<int?>("ScreenHeight")
                        .HasColumnType("integer");

                    b.Property<int?>("ScreenWidth")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("InstallationId")
                        .IsUnique();

                    b.ToTable("Devices", "cognitive");
                });

            modelBuilder.Entity("LtcCognitive.Api.Domain.GameDefinition", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("NameZhTw")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("Games", "cognitive");

                    b.HasData(
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0000-000000000001"),
                            Code = "stroop",
                            IsActive = true,
                            NameZhTw = "顏色文字判斷"
                        },
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0000-000000000002"),
                            Code = "number_order",
                            IsActive = true,
                            NameZhTw = "數字排序"
                        },
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0000-000000000003"),
                            Code = "number_combination",
                            IsActive = true,
                            NameZhTw = "數字組合"
                        },
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0000-000000000004"),
                            Code = "card_memory",
                            IsActive = true,
                            NameZhTw = "翻卡牌"
                        },
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0000-000000000005"),
                            Code = "pipe_rotation",
                            IsActive = true,
                            NameZhTw = "旋轉接水管"
                        });
                });

            modelBuilder.Entity("LtcCognitive.Api.Domain.GameDomainMapping", b =>
                {
                    b.Property<Guid>("GameId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("DomainId")
                        .HasColumnType("uuid");

                    b.Property<string>("MappingVersion")
                        .HasColumnType("text");

                    b.Property<string>("EvidenceNote")
                        .HasColumnType("text");

                    b.Property<decimal>("Weight")
                        .HasPrecision(5, 4)
                        .HasColumnType("numeric(5,4)");

                    b.HasKey("GameId", "DomainId", "MappingVersion");

                    b.HasIndex("DomainId");

                    b.ToTable("GameDomainMappings", "cognitive");
                });

            modelBuilder.Entity("LtcCognitive.Api.Domain.Participant", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AnonymousCode")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<int?>("BirthYear")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DisplayName")
                        .HasColumnType("text");

                    b.Property<string>("EducationBand")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("AnonymousCode")
                        .IsUnique();

                    b.ToTable("Participants", "cognitive");
                });

            modelBuilder.Entity("LtcCognitive.Api.Domain.TrialEvent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ActualResponse")
                        .HasColumnType("text");

                    b.Property<string>("ExpectedResponse")
                        .HasColumnType("text");

                    b.Property<bool?>("IsCorrect")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset>("OccurredAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("PresentationDurationMs")
                        .HasColumnType("integer");

                    b.Property<int?>("ReactionTimeMs")
                        .HasColumnType("integer");

                    b.Property<Guid>("SessionId")
                        .HasColumnType("uuid");

                    b.Property<string>("StimulusJson")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<int>("TrialIndex")
                        .HasColumnType("integer");

                    b.Property<string>("TrialType")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("SessionId", "TrialIndex")
                        .IsUnique();

                    b.ToTable("TrialEvents", "cognitive");
                });

            modelBuilder.Entity("LtcCognitive.Api.Domain.AssessmentSession", b =>
                {
                    b.HasOne("LtcCognitive.Api.Domain.Device", "Device")
                        .WithMany()
                        .HasForeignKey("DeviceId");

                    b.HasOne("LtcCognitive.Api.Domain.GameDefinition", "Game")
                        .WithMany()
                        .HasForeignKey("GameId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LtcCognitive.Api.Domain.Participant", "Participant")
                        .WithMany("Sessions")
                        .HasForeignKey("ParticipantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Device");

                    b.Navigation("Game");

                    b.Navigation("Participant");
                });

            modelBuilder.Entity("LtcCognitive.Api.Domain.DerivedMetric", b =>
                {
                    b.HasOne("LtcCognitive.Api.Domain.CognitiveDomain", "Domain")
                        .WithMany()
                        .HasForeignKey("DomainId");

                    b.HasOne("LtcCognitive.Api.Domain.AssessmentSession", "Session")
                        .WithMany("Metrics")
                        .HasForeignKey("SessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Domain");

                    b.Navigation("Session");
                });

            modelBuilder.Entity("LtcCognitive.Api.Domain.GameDomainMapping", b =>
                {
                    b.HasOne("LtcCognitive.Api.Domain.CognitiveDomain", "Domain")
                        .WithMany()
                        .HasForeignKey("DomainId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LtcCognitive.Api.Domain.GameDefinition", "Game")
                        .WithMany()
                        .HasForeignKey("GameId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Domain");

                    b.Navigation("Game");
                });

            modelBuilder.Entity("LtcCognitive.Api.Domain.TrialEvent", b =>
                {
                    b.HasOne("LtcCognitive.Api.Domain.AssessmentSession", "Session")
                        .WithMany("Trials")
                        .HasForeignKey("SessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Session");
                });

            modelBuilder.Entity("LtcCognitive.Api.Domain.AssessmentSession", b =>
                {
                    b.Navigation("Metrics");

                    b.Navigation("Trials");
                });

            modelBuilder.Entity("LtcCognitive.Api.Domain.Participant", b =>
                {
                    b.Navigation("Sessions");
                });
#pragma warning restore 612, 618
        }
    }
}
